const jsonServer = require('json-server');
const server = jsonServer.create();
const router = jsonServer.router('db.json');
const middleware = jsonServer.defaults();
const port = process.env.PORT || 8080;

const customers = [
  'Sashiranjan',
  'Rupesh',
  'Pratay',
  'Aashish Ranjan',
  'Dipesh',
  'Aniket',
  'BB',
  'Brajesh',
  'Sushil',
  'Gokul HDFC',
  'Manoj',
  'Ajitesh HDFC',
  'Nishant',
  'Ajitesh Roommate HDFC',
  'Chaman',
  'Saurabh HDFC',
  'AK',
  'Satwan SBI Chakla',
  'Papa - 2',
  'S Kumar SBI Chakla',
  'Amit MR',
  'Shyamantak HDFC',
  'Akhilesh SBI',
  'Kundan ICICI',
  'Umesh SBI',
  'Rakesh RBL',
  'Chitranjan SBI',
  'Santosh ITI',
  'Ashish RSM',
  'Ashish Niyojan',
  'Ajit',
  'Pankaj Shani Mandir',
  'Preetesh',
  'Dhananjay IDBI',
  'Akhtar',
  'Sunil IDBI',
  'Saurabh Jhakrahi',
  'Shri Ram Jha Ji',
  'Vikas Thana',
  'Avinash',
  'Ravi Thana',
  'Manish Jio',
  'Imran',
  'Manoranjan',
  'Satendra',
  'Shri Ram 102',
  'AK',
  'Anil',
  'Amit Jha',
  'Sujata',
  'Aman ICICI',
  'Vivek',
  'Sashwat ICICI',
  'Jaiveer Pashupalan',
  'Sanjit ICICI',
  'Vaibhav Shani Mandir',
  'BM ICICI',
  'Neha SS',
  'Shiv Kumar ICICI',
  'Amardeep',
  'Rajendra HDFC',
  'Rupesh',
  'Amit Jha Jivika',
  'Harshvardhan',
  'Aditya Jivika',
  'Amrit',
  'Mary DRCC',
  'Sonu Trajdi',
  'Aftab Trajdi',
  'Vikash Police Line',
  'Santosh Police Line',
  'Arjun Police Line',
  'Vashishth Police Line',
  'Ram Bali Police Line',
  'Amardeep Degree College',
];

server.use(middleware);
server.use(router);

server.listen(port);
